-- Load regulations from StaticContent/documents
-- This script inserts all PDF files found in the documents folder

-- Clear existing regulations first (optional - comment out if you want to keep them)
TRUNCATE TABLE van_ban;

SELECT * FROM van_ban;

INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('1139_qd-dhcntt_20-12-2022_to_chuc_thi_cac_mon_hoc_he_dai_hoc_chinh_quy', '1139_qd-dhcntt_20-12-2022_to_chuc_thi_cac_mon_hoc_he_dai_hoc_chinh_quy.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('1393-qd-dhcntt_29-12-2023_cap_nhat_quy_che_dao_tao_theo_hoc_che_tin_chi_cho_he_dai_hoc_chinh_quy', '1393-qd-dhcntt_29-12-2023_cap_nhat_quy_che_dao_tao_theo_hoc_che_tin_chi_cho_he_dai_hoc_chinh_quy.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('159-qd-dhcntt_05-03-2024_ban_hanh_quy_dinh_kltn', '159-qd-dhcntt_05-03-2024_ban_hanh_quy_dinh_kltn.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('434-qd-dhcntt_07-07-2021_quy_dinh_dao_tao_chuong_trinh_tien_tien', '434-qd-dhcntt_07-07-2021_quy_dinh_dao_tao_chuong_trinh_tien_tien.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('790-qd-dhcntt_28-9-22_quy_che_dao_tao', '790-qd-dhcntt_28-9-22_quy_che_dao_tao.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('Các đợt xét tốt nghiệp đối với sinh viên đại học hệ chính quy', 'Các đợt xét tốt nghiệp đối với sinh viên đại học hệ chính quy.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('Cập nhật Quy chế đào tạo theo học chế tín chỉ  cho hệ đại học chính quy của Trường Đại học Công nghệ Thông tin', 'Cập nhật Quy chế đào tạo theo học chế tín chỉ  cho hệ đại học chính quy của Trường Đại học Công nghệ Thông tin.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('QUY ĐỊNH ĐÀO TẠO CHƯƠNG TRÌNH TÀI NĂNG', 'QUY ĐỊNH ĐÀO TẠO CHƯƠNG TRÌNH TÀI NĂNG.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('Quy trình công nhận tín chỉ trong đào tạo đại học của Trường Đại học Công nghệ Thông tin_', 'Quy trình công nhận tín chỉ trong đào tạo đại học của Trường Đại học Công nghệ Thông tin_.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('Quy trình nộp khóa luận tốt nghiệp sau khi bảo vệ trước Hội đồng bảo vệ khóa luận tốt nghiệp', 'Quy trình nộp khóa luận tốt nghiệp sau khi bảo vệ trước Hội đồng bảo vệ khóa luận tốt nghiệp.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('Quy trình xử lý học vụ sinh viên hệ đại học chính quy', 'Quy trình xử lý học vụ sinh viên hệ đại học chính quy.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('Quy định về Đồ án tốt nghiệp tại doanh nghiệp cho bậc đại học hệ chính quy của Trường Đại học Công nghệ Thông tin', 'Quy định về Đồ án tốt nghiệp tại doanh nghiệp cho bậc đại học hệ chính quy của Trường Đại học Công nghệ Thông tin.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('Quy định đào tạo song ngành trình độ đại học hệ chính quy của Trường Đại học Công nghệ Thông tin', 'Quy định đào tạo song ngành trình độ đại học hệ chính quy của Trường Đại học Công nghệ Thông tin.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('Sửa đổi Quy định đào tạo ngoại ngữ đối với hệ đại học chính quy  của Trường Đại học Công nghệ Thông tin_', 'Sửa đổi Quy định đào tạo ngoại ngữ đối với hệ đại học chính quy  của Trường Đại học Công nghệ Thông tin_.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[DOC]828_qd-dhcntt_04-10-2022_quy_dinh_dao_tao_ngoai_ngu_doi_voi_he_chinh_qui_khoa_2022_0_0 (1)', '[DOC]828_qd-dhcntt_04-10-2022_quy_dinh_dao_tao_ngoai_ngu_doi_voi_he_chinh_qui_khoa_2022_0_0 (1).pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]112-qd-dhcntt_01-02-2024_quy_dinh_dao_tao_song_nganh_trinh_do_dai_hoc_he_chinh_quy', '[OCR]112-qd-dhcntt_01-02-2024_quy_dinh_dao_tao_song_nganh_trinh_do_dai_hoc_he_chinh_quy.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]131-qd-dhcntt_08-03-2022_quy_dinh_dao_tao_chuong_trinh_tai_nang', '[OCR]131-qd-dhcntt_08-03-2022_quy_dinh_dao_tao_chuong_trinh_tai_nang.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]1393-qd-dhcntt_29-12-2023_cap_nhat_quy_che_dao_tao_theo_hoc_che_tin_chi_cho_he_dai_hoc_chinh_quy (1)', '[OCR]1393-qd-dhcntt_29-12-2023_cap_nhat_quy_che_dao_tao_theo_hoc_che_tin_chi_cho_he_dai_hoc_chinh_quy (1).pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]142-tb-dhcntt08-12-2023_2_0', '[OCR]142-tb-dhcntt08-12-2023_2_0.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]1499-qd-dhcntt-10-12-2024', '[OCR]1499-qd-dhcntt-10-12-2024.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]277-qd-dhcntt_21-03-2025', '[OCR]277-qd-dhcntt_21-03-2025.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]364-qd-dhcntt_22-04-2024_sua_doi_quy_dinh_dao_tao_ngoai_ngu', '[OCR]364-qd-dhcntt_22-04-2024_sua_doi_quy_dinh_dao_tao_ngoai_ngu.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]412-qd-dhcntt_27-03-2025_quy_trinh_cong_nhan_tin_chi_trong_dao_tao_dai_hoc', '[OCR]412-qd-dhcntt_27-03-2025_quy_trinh_cong_nhan_tin_chi_trong_dao_tao_dai_hoc.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]560-qd-dhcntt_5-6-2024_sua_doi_quy_dinh_dao_tao_ngoai_ngu_doi_voi_he_dai_hoc_chinh_quy', '[OCR]560-qd-dhcntt_5-6-2024_sua_doi_quy_dinh_dao_tao_ngoai_ngu_doi_voi_he_dai_hoc_chinh_quy.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]583-qd-dhcntt_12-6-2023_ban_hanh_quy_trinh_nop_kltn_sau_khi_bao_ve_truoc_hoi_dong_bao_ve_kltn', '[OCR]583-qd-dhcntt_12-6-2023_ban_hanh_quy_trinh_nop_kltn_sau_khi_bao_ve_truoc_hoi_dong_bao_ve_kltn.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]697-qd-dhcntt_12-7-2024_quy_dinh_do_an_tot_nghiep_tai_doanh_nghiep', '[OCR]697-qd-dhcntt_12-7-2024_quy_dinh_do_an_tot_nghiep_tai_doanh_nghiep.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]803-qd-dhcntt_11-07-2025_quy_trinh_xlhv', '[OCR]803-qd-dhcntt_11-07-2025_quy_trinh_xlhv.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]828_qd-dhcntt_04-10-2022_quy_dinh_dao_tao_ngoai_ngu_doi_voi_he_chinh_qui_khoa_2022_0_0 (1)', '[OCR]828_qd-dhcntt_04-10-2022_quy_dinh_dao_tao_ngoai_ngu_doi_voi_he_chinh_qui_khoa_2022_0_0 (1).pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('[OCR]851-qd-dhcntt-14-08-2024-scan', '[OCR]851-qd-dhcntt-14-08-2024-scan.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('_Quy định về Liêm chính học thuật tại Trường Đại học Công nghệ Thông tin', '_Quy định về Liêm chính học thuật tại Trường Đại học Công nghệ Thông tin.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
INSERT INTO van_ban (ten_van_ban, url_van_ban, ngay_ban_hanh) VALUES ('_Quy định về đồ án tốt nghiệp của Trường Đại học Công nghệ Thông tin', '_Quy định về đồ án tốt nghiệp của Trường Đại học Công nghệ Thông tin.pdf', NULL) ON CONFLICT (ten_van_ban) DO UPDATE SET url_van_ban = EXCLUDED.url_van_ban, ngay_ban_hanh = EXCLUDED.ngay_ban_hanh;
